### ISSUE TITLE
Local Videos

### ISSUE THREAD

**Issue by aaronpeloquin** [louy/VideoPlayer#1]
I am attempting to have this play local video content using phonegap v2.9.0. The javascript is all working up until I try to play a video, but then nothing happens.

Any advice?

How I'm calling the video is:
window.plugins.VideoPlugin.play("file:///android_assets/www/videos/"+video_name+".mp4");

Where the video_name variable is the name of that video in my videos folder.

Thank you

**Comment by louy** [comment]
This plugin doesn't support playing local videos. Try the original plugin https://github.com/macdonst/VideoPlayer
The original one didn't work for me so I had to remove the functionality that I didn't need (including playing local videos) and this is why I created this. Also I am not a Java developer after all :)
